title: Visual Framework Text
label: Text
status: live
context:
  component-type: element
variants:
  - name: default
    hidden: true
  - name: extra-large
    context:
      text: This text is extra large
      type: 1
  - name: large
    context:
      text: This text is large
      type: 2
  - name: regular
    context:
      text: This text is regular
      type: 3
  - name: small
    context:
      text: This text is small
      type: 4
  - name: extra-small
    context:
      text: This text is extra small
      type: 5
