title: Navigation
label: Navigation
preview: '@preview--nogrid'
status: live

context:
  component-type: block

variants:
  - name: default
    hidden: true

  - name: global
    context:
      classModifier: global
      navigation:
        - text: Services
          navigation_href: JavaScript:Void(0);
        - text: Research
          navigation_href: JavaScript:Void(0);
        - text: Training
          navigation_href: JavaScript:Void(0);
        - text: About us
          navigation_href: JavaScript:Void(0);

  - name: main
    context:
      classModifier: main
      navigation:
        - text: Home
          navigation_href: JavaScript:Void(0);
          currentPage: balls
        - text: Download
          navigation_href: JavaScript:Void(0);
        - text: Release Notes
          navigation_href: JavaScript:Void(0);
        - text: FAQ
          navigation_href: JavaScript:Void(0);
        - text: Help
          navigation_href: JavaScript:Void(0);
        - text: Licence
          navigation_href: JavaScript:Void(0);
        - text: About
          navigation_href: JavaScript:Void(0);
        - text: Feedback
          navigation_href: JavaScript:Void(0);


  - name: additional
    status: deprecated
    hidden: true
    context:
      component-type: deprecated

      heading: European Bioinformatics Institute
      classModifier: additional
      title: European Bioinformatics Institute
      navigation:
        - text: services
          navigation_href: JavaScript:Void(0);
        - text: research
          navigation_href: JavaScript:Void(0);
        - text: training
          navigation_href: JavaScript:Void(0);
        - text: about us
          navigation_href: JavaScript:Void(0);
