title: Textarea
label: Textarea
status: beta

context:
  component-type: form
  text_area_rows: 5
  text_area_name: text-area
  text_label:
    form__label: Write Some More details
    form__label_for: text-area
