title: Summary
label: Summary
status: live
context:
  component-type: block

  summary__title: What is Cancer?
  summary__text: Cancer is a group of diseases involving abnormal cell growth with the potential to invade or spread to other parts of the body.
  image: /assets/vf-summary/assets/vf-icon--avatar.svg
  name: FirstName Surname
  summary__href: 'JavaScript:Void(0);'
variants:
  - name: profile
    context:
      email: contact@persons.com
      phone: +49 6221 387 8443
      mobile: +49 1758 991 179
      text: EMBL Press Office
      uuid: 0000 - 1234 - 4326 - XX03
  - name: large
    context:
      size: l
  - name: regular
    context:
      size: r
      email: contact@persons.com
  - name: small
    context:
      size: s
