title: Breadcrumbs
label: Breadcrumbs
status: live
context:
  exampleMultiColumns: "false"
  component-type: block
  breadcrumbs:
    - text: Explore
      breadcrumb_href: JavaScript:Void(0);
    - text: Topics
      breadcrumb_href: JavaScript:Void(0);
    - text: Centre
      currentPage: true
  related:
    - text: Biscuits
      breadcrumb_href: JavaScript:Void(0);
    - text: Fruits For Cheese
      breadcrumb_href: JavaScript:Void(0);
