title: Breadcrumbs
label: Breadcrumbs
status: beta
context:
  component-type: block
  breadcrumbs:
    - text: Explore
      breadcrumb_href: JavaScript:Void(0);
    - text: Topics
      breadcrumb_href: JavaScript:Void(0);
    - text: Centre
  related:
    - text: Biscuits
      breadcrumb_href: JavaScript:Void(0);
    - text: Fruits For Cheese
      breadcrumb_href: JavaScript:Void(0);
