title: Divider
label: Divider
status: live
preview: '@preview--body'
context:
  exampleMultiColumns: "false"
  component-type: element
variants:
  - name: default
  - name: fullbleed
    context:
      override_class: vf-u-fullbleed
  - name: fullbleed custom
    context:
      override_class: vf-u-fullbleed
      context_margin__inline: 3rem
