title: Video Teaser
label: Video Teaser
preview: '@preview--blocks'
context:
  component-type: block
  vf_video_teaser__title: More on our YouTube channel
  vf_video_teaser__link: New theory deepens understanding of Turing patterns
