# The title shown on the component page
title: Lede
# Label shown on index pages
label: Lede
status: alpha
# The template used from /components/_previews
preview: '@preview--blocks'
# Per-variant options
# variants:
  # - name: default
  #   hidden: true
context:
  component-type: block
  # custom-values: passed as {{custom-values}}
  vf-lede-text: Lede text is a generic type of conent for different diseases in which cells divide many more times than usual. <a href="#">This abnormal growth</a> can affect many cell types in almost any part of the body.
