# The title shown on the pattern page
title: Lede
# Label shown on index pages
label: Lede
status: alpha
# The template used from /components/_previews
# preview: '@preview--blocks'
# Per-variant options
# variants:
  # - name: default
  #   hidden: true
context:
  pattern-type: block
  # custom-values: passed as {{custom-values}}
  vf-lede-text: Cancer is a generic term for lots of different diseases in which cells divide many more times than usual. This abnormal growth can affect many cell types in almost any part of the body.
