title: Masthead
label: Masthead
preview: '@preview--nogrid'
status: live

context:
  component-type: block

  masthead_href: 'JavaScript:Void(0);'

variants:
  - name: default
  - name: primary
    context:
      mastheadTheme: primary
  - name: secondary
    context:
      mastheadTheme: secondary
  - name: tertiary
    context:
      mastheadTheme: tertiary

  - name: title block
    context:
      hasTitleBlock: true

  - name: title block (primary)
    context:
      hasTitleBlock: true
      mastheadTheme: primary

  - name: image
    context:
      mastheadImage: "https://acxngcvroo.cloudimg.io/v7/https://www.embl.org/files/wp-content/uploads/VF_Masthead_Example_52ACEA.jpg"

  - name: title block and image
    context:
      mastheadImage: "https://acxngcvroo.cloudimg.io/v7/https://www.embl.org/files/wp-content/uploads/VF_Masthead_Example_52ACEA.jpg"
      hasTitleBlock: true

