title: Section Header
label: Section Header
status: live
context:
  component-type: block
  section_title: Projects
variants:
  - name: default
    title: Default
    id: section-default
  - name: is a link
    title: Is a link
    context:
      id: section-link
      href: JavaScript:Void(0);
  - name: has a sub-heading
    title: Has a sub-heading
    context:
      id: section-sub-heading
      section__subheading: News from EMBL’s six sites
  - name: has a sub-heading and link
    title: Has a sub-heading and link
    context:
      href: JavaScript:Void(0);
      id: section-sub-heading-link
      section__subheading: News from EMBL’s six sites
  - name: has a sub-heading and link and text
    context:
      href: JavaScript:Void(0);
      id: section-sub-heading-link-text
      section__subheading: News from EMBL’s six sites
      vf_section__content:
      - Hello everyone who are doing?
      - Buy <a href="#">Pizza</a>.
  - name: has a link and text
    context:
      href: JavaScript:Void(0);
      id: section-link-text
      vf_section__content:
      - Hello everyone who are doing?
      - Pizza
  - name: has text
    context:
      id: section-text
      vf_section__content:
      - Hello everyone who are doing?
      - Pizza
