# The title shown on the component page
title: Search
# Label shown on index pages
label: Search
status: beta
collated: true
# The template used from /components/_previews
#
# Per-variant options
variants:
  - name: default
    label: Default
    hidden: false
    context:
      variant: default
      search_action: '#'
      search_autofocus: true
      search_button: Search
      search_label: Search
      search_placeholder: Enter your search terms
      search_id: searchitem
      search_value_default: ''
  - name: inline
    label: Inline
    hidden: false
    context:
      variant: inline
      search_action: '#'
      search_autofocus: true
      search_button: Search
      search_label: Inline search
      search_placeholder: Enter your search terms
      search_id: inlinesearchitem
      search_value_default: ''
context:
  component-type: block
  # custom-values: passed as {{custom-values}}
