title: Article Meta Information
label: Article Meta Information
status: beta

context:
  component-type: block

  author__name: First-Name Surame
  author__avatar: https://avatars3.githubusercontent.com/u/925197?s=88&v=4
  meta__topics:
    - cancer
    - history
  meta__date: 14th February 2019
  meta__comment_count: 61
  meta__links_title: On This Page
  meta__links:
    - heading link 1
    - heading link 2
    - heading link 3
    - heading link 4
    - heading link 5
    - heading link 6
  meta__url: 'https://example.com'
