title: Article Meta Information
label: Article Meta Information
status: beta
context:
  component-type: block
  author__name: First-Name Surname
  author__avatar: https://avatars3.githubusercontent.com/u/925197?s=88&v=4
  meta__topics:
    - cancer
    - history
  meta__date: 14 February 2019
  meta__comment_count: 61
  meta__links_title: On this page
  meta__links:
    - text: heading link 1
      url: 'JavaScript:Void(0);'
    - text: heading link 2
      url: 'JavaScript:Void(0);'
    - text: heading link 3
      url: 'JavaScript:Void(0);'
    - text: heading link 4
      url: 'JavaScript:Void(0);'
    - text: heading link 5
      url: 'JavaScript:Void(0);'
    - text: heading link 6
      url: 'JavaScript:Void(0);'
  meta__url: 'JavaScript:Void(0);'
