title: EMBL Breadcrumbs lookup
label: EMBL Breadcrumbs

status: alpha
context:
  component-type: embl-block
  meta-who: Strategy and Communications
  meta-what: Visual Framework
  meta-where: EMBL
  meta-active: what
  meta-utility: -8
  meta-reach: -5
  meta-maintainer: Strategy and Communications
  meta-last-review: "2019-01-20"
  meta-review-cycle: 180
  meta-expiry: "2019-06-20"
