# The title shown on the component page
title: EMBL Notifications
# Label shown on index pages
label: EMBL Notifications
status: live
# The template used from /components/_previews
#
# Per-variant options
variants:
  - name: default
    hidden: true
context:
  component-type: utility
  # custom-values: passed as {{custom-values}}
  # - note: you in your custom-values you should use dashes `-`
  #         and not underscores `_` as underscores prevent inherited template use
  # title: Title text
  # text: String of text
  # image: ../../assets/vf-component-name/assets/vf-component-name.png
  # - note on paths: be sure to prefix with `../../`
  # - Why? https://github.com/visual-framework/vf-core/issues/364
