title: Visual Framework Headings
label: Headings
status: beta
context:
  component-type: element
variants:
  - name: default
    hidden: true
  - name: display
    context:
      type: 1
      heading: This heading size is extra large and inverted
      style: invert
      tags: h1
  - name: extra-large
    context:
      type: 2
      heading: This heading size is extra large
      tags: h1
  - name: large
    context:
      type: 3
      heading: This heading size is large
      tags: h2
  - name: regular
    context:
      type: 4
      heading: This heading size is regular
      tags: h3
  - name: small
    context:
      type: 5
      heading: This heading size is small
      tags: h4
