# The title shown on the component page
title: Reusable Design Tokens
# Label shown on index pages
label: Design Tokens
status: beta
# The template used from /components/_previews
#
# Per-variant options
variants:
  - name: default
context:
  component-type: utility
  # custom-values: passed as {{custom-values}}
  # title: Title text
  # text: String of text
  # image: ../../assets/vf-component-name/assets/vf-component-name.png
  # - note on paths: be sure to prefix with `../../`
  # - Why? https://github.com/visual-framework/vf-core/issues/364
