title: Links List
label: Links List
context:
  component-type: block
status: deprecated
component-type: deprecated
hidden: true
variants:
  - name: default
    context:
      title: Latest Posts
      list:
        - text: VF’s top social media posts of 2017 and what we learned from them
          link_list_href: JavaScript:Void(0);
        - text: The VF Imaging Centre all about visibility
          link_list_href: JavaScript:Void(0);
        - text: Press office sprint 1 journalist personas
          link_list_href: JavaScript:Void(0);
        - text: A colour scheme for VF
          link_list_href: JavaScript:Void(0);
          badge:
            theme: secondary
            text: alpha
          meta: Updated 14th February 2018
        - text: New team members
          link_list_href: JavaScript:Void(0);
  - name: No Heading
    context:
      list:
        - text: VF’s top social media posts of 2017 and what we learned from them
          link_list_href: JavaScript:Void(0);
        - text: The VF Imaging Centre all about visibility
          link_list_href: JavaScript:Void(0);
        - text: Press office sprint 1 journalist personas
          link_list_href: JavaScript:Void(0);
        - text: A colour scheme for VF
          link_list_href: JavaScript:Void(0);
          badge:
            theme: secondary
            text: alpha
          meta: Updated 14th February 2018
        - text: New team members
          link_list_href: JavaScript:Void(0);
  - name: tight
    context:
      component_modifier: vf-links--tight vf-links__list--s
      title: Latest Posts
      list_modifier: secondary
      list:
        - text: All
          meta: 39
        - text: Administration
          meta: 39
        - text: Bioninformatics
          meta: 39
        - text: Communication
          meta: 39
        - text: Data Curation
          meta: 39
        - text: General Support Services
          meta: 39
        - text: IT and Infrastructure
          meta: 39

  - name: very easy
    context:
      component_modifier: vf-links--tight vf-links__list--s vf-links__list--very-easy
      title: In this section
      list_modifier: secondary
      list:
        - text: All
          link_list_href: JavaScript:Void(0);
        - text: Administration
          link_list_href: JavaScript:Void(0);
        - text: Bioninformatics
          link_list_href: JavaScript:Void(0);
        - text: Communication
          link_list_href: JavaScript:Void(0);
        - text: Data Curation
          link_list_href: JavaScript:Void(0);
        - text: General Support Services
          link_list_href: JavaScript:Void(0);
        - text: IT and Infrastructure
          link_list_href: JavaScript:Void(0);

  - name: easy
    context:
      component_modifier: vf-links__list--easy
      title: On this page
      svg: true
      list:
        - text: All
          link_list_href: JavaScript:Void(0);
        - text: Administration
          link_list_href: JavaScript:Void(0);
          meta: Updated 14th February 2018
        - text: Bioninfomatics
          link_list_href: JavaScript:Void(0);
        - text: Communication
          link_list_href: JavaScript:Void(0);
        - text: Data Curation
          link_list_href: JavaScript:Void(0);
        - text: General Support Services
          link_list_href: JavaScript:Void(0);
        - text: IT and Infrastructure
          link_list_href: JavaScript:Void(0);
  - name: has images
    context:
      title: Services
      list_modifier: has-image
      list:
        - text: BioMedBridges
          image: <svg class="vf-list__image" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><path d="M30.184 21.298c-1.416-1.411-3.467-1.959-5.388-1.663l-9.179-9.181c.083-.244.141-.49.141-.702V5.306c0-.545-.4-1.193-.889-1.433L8.072.471C7.583.23 6.871.344 6.484.73l-.741.74a.992.992 0 0 0 0 1.402l3.956 3.956a.995.995 0 0 1 0 1.402l-1.813 1.814a.994.994 0 0 1-1.401 0L2.528 6.088a.999.999 0 0 0-1.402 0l-.739.739C0 7.211-.116 7.929.128 8.413l3.399 6.8c.247.485.892.885 1.437.885l4.446.002c.213 0 .46-.059.706-.142l9.49 9.491c-.067 1.676.519 3.373 1.792 4.652a6.185 6.185 0 0 0 4.395 1.816 6.197 6.197 0 0 0 4.398-1.82c2.413-2.424 2.413-6.37-.007-8.799zm-2.514 6.279c-1.007 1.004-2.757.993-3.753.006a2.673 2.673 0 0 1-.004-3.761 2.645 2.645 0 0 1 1.879-.776 2.64 2.64 0 0 1 1.872.771 2.672 2.672 0 0 1 .006 3.76z"/></svg>
        - text: BioSamples
          image: <img class="vf-list__image" src="https://www.ebi.ac.uk/sites/ebi.ac.uk/files/styles/icon/public/resource/thumbnail/biosamples_serviceicon.jpg">
        - text: EFO
          image: <svg class="vf-list__image" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><path d="M30.184 21.298c-1.416-1.411-3.467-1.959-5.388-1.663l-9.179-9.181c.083-.244.141-.49.141-.702V5.306c0-.545-.4-1.193-.889-1.433L8.072.471C7.583.23 6.871.344 6.484.73l-.741.74a.992.992 0 0 0 0 1.402l3.956 3.956a.995.995 0 0 1 0 1.402l-1.813 1.814a.994.994 0 0 1-1.401 0L2.528 6.088a.999.999 0 0 0-1.402 0l-.739.739C0 7.211-.116 7.929.128 8.413l3.399 6.8c.247.485.892.885 1.437.885l4.446.002c.213 0 .46-.059.706-.142l9.49 9.491c-.067 1.676.519 3.373 1.792 4.652a6.185 6.185 0 0 0 4.395 1.816 6.197 6.197 0 0 0 4.398-1.82c2.413-2.424 2.413-6.37-.007-8.799zm-2.514 6.279c-1.007 1.004-2.757.993-3.753.006a2.673 2.673 0 0 1-.004-3.761 2.645 2.645 0 0 1 1.879-.776 2.64 2.64 0 0 1 1.872.771 2.672 2.672 0 0 1 .006 3.76z"/></svg>
        - text: EGA
          image: <svg class="vf-list__image" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><path d="M30.184 21.298c-1.416-1.411-3.467-1.959-5.388-1.663l-9.179-9.181c.083-.244.141-.49.141-.702V5.306c0-.545-.4-1.193-.889-1.433L8.072.471C7.583.23 6.871.344 6.484.73l-.741.74a.992.992 0 0 0 0 1.402l3.956 3.956a.995.995 0 0 1 0 1.402l-1.813 1.814a.994.994 0 0 1-1.401 0L2.528 6.088a.999.999 0 0 0-1.402 0l-.739.739C0 7.211-.116 7.929.128 8.413l3.399 6.8c.247.485.892.885 1.437.885l4.446.002c.213 0 .46-.059.706-.142l9.49 9.491c-.067 1.676.519 3.373 1.792 4.652a6.185 6.185 0 0 0 4.395 1.816 6.197 6.197 0 0 0 4.398-1.82c2.413-2.424 2.413-6.37-.007-8.799zm-2.514 6.279c-1.007 1.004-2.757.993-3.753.006a2.673 2.673 0 0 1-.004-3.761 2.645 2.645 0 0 1 1.879-.776 2.64 2.64 0 0 1 1.872.771 2.672 2.672 0 0 1 .006 3.76z"/></svg>
        - text: EMMA
          image: <svg class="vf-list__image" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><path d="M30.184 21.298c-1.416-1.411-3.467-1.959-5.388-1.663l-9.179-9.181c.083-.244.141-.49.141-.702V5.306c0-.545-.4-1.193-.889-1.433L8.072.471C7.583.23 6.871.344 6.484.73l-.741.74a.992.992 0 0 0 0 1.402l3.956 3.956a.995.995 0 0 1 0 1.402l-1.813 1.814a.994.994 0 0 1-1.401 0L2.528 6.088a.999.999 0 0 0-1.402 0l-.739.739C0 7.211-.116 7.929.128 8.413l3.399 6.8c.247.485.892.885 1.437.885l4.446.002c.213 0 .46-.059.706-.142l9.49 9.491c-.067 1.676.519 3.373 1.792 4.652a6.185 6.185 0 0 0 4.395 1.816 6.197 6.197 0 0 0 4.398-1.82c2.413-2.424 2.413-6.37-.007-8.799zm-2.514 6.279c-1.007 1.004-2.757.993-3.753.006a2.673 2.673 0 0 1-.004-3.761 2.645 2.645 0 0 1 1.879-.776 2.64 2.64 0 0 1 1.872.771 2.672 2.672 0 0 1 .006 3.76z"/></svg>
        - text: ENA
          image: <svg class="vf-list__image" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><path d="M30.184 21.298c-1.416-1.411-3.467-1.959-5.388-1.663l-9.179-9.181c.083-.244.141-.49.141-.702V5.306c0-.545-.4-1.193-.889-1.433L8.072.471C7.583.23 6.871.344 6.484.73l-.741.74a.992.992 0 0 0 0 1.402l3.956 3.956a.995.995 0 0 1 0 1.402l-1.813 1.814a.994.994 0 0 1-1.401 0L2.528 6.088a.999.999 0 0 0-1.402 0l-.739.739C0 7.211-.116 7.929.128 8.413l3.399 6.8c.247.485.892.885 1.437.885l4.446.002c.213 0 .46-.059.706-.142l9.49 9.491c-.067 1.676.519 3.373 1.792 4.652a6.185 6.185 0 0 0 4.395 1.816 6.197 6.197 0 0 0 4.398-1.82c2.413-2.424 2.413-6.37-.007-8.799zm-2.514 6.279c-1.007 1.004-2.757.993-3.753.006a2.673 2.673 0 0 1-.004-3.761 2.645 2.645 0 0 1 1.879-.776 2.64 2.64 0 0 1 1.872.771 2.672 2.672 0 0 1 .006 3.76z"/></svg>
        - text: GO
          image: <img class="vf-list__image" src="https://www.ebi.ac.uk/sites/ebi.ac.uk/files/styles/icon/public/resource/thumbnail/go-logo-cropped-2013.jpg">
        - text: no image
          image: blank
        - text: GWAS Catalog
          image: <img class="vf-list__image" src="https://www.ebi.ac.uk/sites/ebi.ac.uk/files/styles/icon/public/resource/thumbnail/gwas_catalog_logo_73x73.png">
        - text: IMPC Portal
          image: <img class="vf-list__image" src="https://www.ebi.ac.uk/sites/ebi.ac.uk/files/styles/icon/public/resource/thumbnail/impc_logo_icon.png">
        - text: OLS
          image: <svg class="vf-list__image" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><path d="M30.184 21.298c-1.416-1.411-3.467-1.959-5.388-1.663l-9.179-9.181c.083-.244.141-.49.141-.702V5.306c0-.545-.4-1.193-.889-1.433L8.072.471C7.583.23 6.871.344 6.484.73l-.741.74a.992.992 0 0 0 0 1.402l3.956 3.956a.995.995 0 0 1 0 1.402l-1.813 1.814a.994.994 0 0 1-1.401 0L2.528 6.088a.999.999 0 0 0-1.402 0l-.739.739C0 7.211-.116 7.929.128 8.413l3.399 6.8c.247.485.892.885 1.437.885l4.446.002c.213 0 .46-.059.706-.142l9.49 9.491c-.067 1.676.519 3.373 1.792 4.652a6.185 6.185 0 0 0 4.395 1.816 6.197 6.197 0 0 0 4.398-1.82c2.413-2.424 2.413-6.37-.007-8.799zm-2.514 6.279c-1.007 1.004-2.757.993-3.753.006a2.673 2.673 0 0 1-.004-3.761 2.645 2.645 0 0 1 1.879-.776 2.64 2.64 0 0 1 1.872.771 2.672 2.672 0 0 1 .006 3.76z"/></svg>
