title: EMBL Grid
label: EMBL Grid
preview: '@preview--nogrid'
status: live
context:
  component-type: embl-grid

variants:
  - name: default
    hidden: true
  - name: has-sidebar
    label: Sidebar
    context:
      embl_grid__type: sidebar
  - name: hairline
    label: Hairline
    context:
      embl_grid__type: sidebar
      embl_grid__hairline: true
  - name: has-centered-content
    label: Centered
    context:
      embl_grid__type: centered
