title: Global Header
label: Global Header
preview: '@preview--nogrid'
status: live

context:
  exampleMultiColumns: "false"
  component-type: block
  global_logo:
    logo_href: /
    image: ../../assets/vf-logo/assets/logo.svg
    logo_text: Visual Framework for Life Science websites
