# The title shown on the component page
title: Card Container
# Label shown on index pages
label: Card Container
status: alpha
preview: '@preview--nogrid'
# The template used from /components/_previews
#
# Per-variant options
# variants:
  # - name: default
  #   hidden: true
context:
  component-type: container
  # custom-values: passed as {{custom-values}}
  # title: Title text
  # text: String of text
  # image: ../../assets/vf-component-name/assets/vf-component-name.png
  # - note on paths: be sure to prefix with `../../`
  # - Why? https://github.com/visual-framework/vf-core/issues/364
