title: Stack
label: Stack
status: beta

context:
  component-type: layout

variants:
  - name: default
    hidden: true
  - name: "200"
    label: Spacing (200)
    context:
      stack__spacing: 200
  - name: "400"
    label: Spacing (400)
    context:
      stack__spacing: 400
  - name: "500"
    label: Spacing (500)
    context:
      stack__spacing: 500
  - name: "600"
    label: Spacing (600)
    context:
      stack__spacing: 600
  - name: "800"
    label: Spacing (800)
    context:
      stack__spacing: 800
  - name: "1200"
    label: Spacing (1200)
    context:
      stack__spacing: 1200
  - name: "1600"
    label: Spacing (1600)
    context:
      stack__spacing: 1600
  - name: custom
    label: Spacing (custom)
    context:
      stack__spacing__custom: 4rem
      stack__spacing: custom
