# The title shown on the pattern page
title: Discussion
# Label shown on index pages
label: Discussion
status: alpha
# The template used from /components/_previews
#
# Per-variant options
# variants:
  # - name: default
  #   hidden: true
context:
  component-type: block
  # custom-values: passed as {{custom-values}}

  number: 3
  text:  comments on 'EMBL's graphic design history'
  discussions:
    - name: Title If Relevant
      date: 15th February 2018
      imageUrl: "/assets/vf-summary/assets/vf-summary--profile-img.png"
      content:
        <p>Really enjoyed reading this post, thank you.</p>
        <p>For me, any communications strategy should be deeply rooted in the organisational strategy. And yet, your closing question reminded me how the discussions we lead about communications can often result in much broader discussions on organisational goals, ambitions and approaches.</p>
      button_text: Reply
    - name: Title If Relevant
      date: 15th February 2018
      imageUrl: "/assets/vf-summary/assets/vf-summary--profile-img.png"
      content:
        <p>Really enjoyed reading this post, thank you.</p>
      button_text: Reply
      secondary_button: Optional action
      vf_discussion_href: 'JavaScript:Void(0);'
      nested:
      - name: Mr. Nested
        date: 16th Febraury 2018
        imageUrl: "/assets/vf-summary/assets/vf-summary--profile-img.png"
        content:
          <p>Really enjoyed reading this post, thank you.</p>
        button_text: Reply
