title: Blockquote
label: Blockquote
status: live

context:
  component-type: element

variants:
  - name: default
    context:
      blockquote_text: '"Look back to move forwards" is a well-known saying. Thus, I recently turned to VF’s archivist, Anne-Flore Laloë, who helped me to search VF’s amazing archive to learn how VF has depicted itself through the years. Maybe knowing more about our first visual identity could help us better.'
      blockquote_citation: 'Someone <a href="#">Really F. Amous</a> said this.'
