title: Acivity List Group
label: Acivity List Group
preview: '@preview--nogrid'
status: deprecated
component-type: deprecated
hidden: true
context:
  component-type: container
  heading: Recent activity

  activity_list__1:
    date: "24th January 2019"
    list:
      - <strong>Sonia Furtado Neves</strong> published <a href="JavaScript:Void(0);">'The Future of Training'</a> on <a href="JavaScript:Void(0);">EMBL News</a>.
      - <strong>Mark Boulton</strong> updated <a href="JavaScript:Void(0);">Digital Strategy</a> on <a href="JavaScript:Void(0);">Gitlab</a> to version 1.1, with the comment <blockquote class="vf-activity__blockquote | vf-blockquote">Additional detail added to social section.</blockquote>

  activity_list__2:
    date: "29th January 2019"
    list:
      - <strong>Mark Boulton</strong> updated <a href="JavaScript:Void(0);">Digital Strategy</a> on <a href="JavaScript:Void(0);">Gitlab</a> to version 1.1, with the comment <blockquote class="vf-activity__blockquote | vf-blockquote">Additional detail added to social section.</blockquote>
      - <strong>Sonia Furtado Neves</strong> published <a href="JavaScript:Void(0);">'The Future of Training'</a> on <a href="JavaScript:Void(0);">EMBL News</a>.
      - <strong>Sonia Furtado Neves</strong> published <a href="JavaScript:Void(0);">'The Future of Training'</a> on <a href="JavaScript:Void(0);">EMBL News</a>.


  activity_list__3:
    date: "30th January 2019"
    list:
      - <strong>Sonia Furtado Neves</strong> published <a href="JavaScript:Void(0);">'The Future of Training'</a> on <a href="JavaScript:Void(0);">EMBL News</a>.
      - <strong>Sonia Furtado Neves</strong> published <a href="JavaScript:Void(0);">'The Future of Training'</a> on <a href="JavaScript:Void(0);">EMBL News</a>.
      - <strong>Mark Boulton</strong> updated <a href="JavaScript:Void(0);">Digital Strategy</a> on <a href="JavaScript:Void(0);">Gitlab</a> to version 1.1, with the comment <blockquote class="vf-activity__blockquote | vf-blockquote">Additional detail added to social section.</blockquote>
