title: Favicon
label: Favicon
status: live
context:
  component-type: element
variants:
  - name: default
    context:
      apple_touch_icon: https://dev.assets.emblstatic.net/vf/develop/assets/vf-favicon/assets/apple-touch-icon.png
      icon_32: https://dev.assets.emblstatic.net/vf/develop/assets/vf-favicon/assets/favicon-32x32.png
      icon_16: https://dev.assets.emblstatic.net/vf/develop/assets/vf-favicon/assets/favicon-16x16.png
      manifest: https://dev.assets.emblstatic.net/vf/develop/assets/vf-favicon/assets/site.webmanifest
      icon_mask: https://dev.assets.emblstatic.net/vf/develop/assets/vf-favicon/assets/safari-pinned-tab.svg
      color_mask: '#ffffff'
      color_msapplication: '#ffffff'
      color_theme: '#ffffff'
