title: Banner
label: Banner
status: live

context:
  component-type: container
  data-service-id: MyService
  data-protection-version: 0.1
  vf-data-protection-banner__text: I agree, dismiss this banner
  vf-data-protection-banner__link:
  vf-banner--inline_href: 'JavaScript:Void(0);'
variants:
  - name: default
    hidden: true
