# The title shown on the component page
title: Card
# Label shown on index pages
label: Card
status: alpha
# preview: '@preview--nogrid'
# The template used from /components/_previews
#
context:
  component-type: block
  # modifier: vf-u-background-color--grey--lightest
# Per-variant options
variants:
  - name: default
    label: default
    context:
      card_title: A Default Card Title
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: Default with Link
    label: Default with Link
    hidden: false
    context:
      card_title: A Default With Link Card Title
      card_href: "JavaScript:Void(0);"
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text

  - name: Bordered
    label: Bordered
    hidden: false
    context:
      card_title: A Bordered Card Title
      variant: bordered
      newTheme: primary
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: Bordered Secondary
    label: Bordered / Secondary
    hidden: true
    context:
      card_title: A Bordered Card Title
      variant: bordered
      newTheme: secondary
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: Bordered Tertiary
    label: Bordered / Tertiary
    hidden: true
    context:
      card_title: A Bordered Card Title
      variant: bordered
      newTheme: tertiary
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: Bordered with Link
    label: Bordered with Link
    hidden: false
    context:
      card_title: A Bordered With Link Card Title
      variant: bordered
      newTheme: primary
      card_href: "JavaScript:Void(0);"
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text

  - name: Striped
    label: Striped
    hidden: false
    context:
      card_title: A Striped Card Title
      variant: striped
      newTheme: primary
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: Striped Secondary
    label: Striped / Secondary
    hidden: true
    context:
      card_title: A Striped Card Title
      variant: striped
      newTheme: secondary
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: Striped Tertiary
    label: Striped / Tertiary
    hidden: true
    context:
      card_title: A Striped Card Title
      variant: striped
      newTheme: tertiary
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: striped-link
    label: Striped with link
    hidden: false
    context:
      card_title: A Striped Card Title with Link
      variant: striped
      newTheme: primary
      card_href: "JavaScript:Void(0);"
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, <a class="vf-card__link" href="JavaScript:Void(0);">consectetur</a> adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text

  - name: very-easy
    label: Very Easy
    hidden: true
    context:
      card_title: A Easy Card Title 1
      variant: very-easy
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: easy
    label: Easy
    hidden: true
    context:
      card_title: A Easy Card Title 2
      variant: easy
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: easy--primary
    label: Easy (primary)
    hidden: true
    context:
      card_title: Easy Card with primary accent
      theme: primary
      variant: easy
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: easy--secondary
    label: Easy (secondary)
    hidden: true
    context:
      theme: secondary
      variant: easy
      card_title: A Easy Card with secondary accent
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: easy--tertiary
    label: Easy (tertiary)
    hidden: true
    context:
      theme: tertiary
      variant: easy
      card_title: A Easy Card with tertiary accent
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: easy--quaternary
    label: Easy (quaternary)
    hidden: true
    context:
      theme: quaternary
      variant: easy
      card_title: A Easy Card with quaternary accent
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: normal
    label: Normal
    hidden: true
    context:
      card_title: A Normal Card
      variant: normal
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: normal--primary
    label: Normal (primary)
    hidden: true
    context:
      card_title: A Normal Card with primary accent
      theme: primary
      variant: normal
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: normal--secondary
    label: Normal (secondary)
    hidden: true
    context:
      theme: secondary
      variant: normal
      card_title: A Normal Card with secondary accent
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: normal--tertiary
    label: Normal (tertiary)
    hidden: true
    context:
      theme: tertiary
      variant: normal
      card_title: A Normal Card with tertiary accent
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: normal--quaternary
    label: Normal (quaternary)
    hidden: true
    context:
      theme: quaternary
      variant: normal
      card_title: A Normal Card with quaternary accent
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
  - name: normal--primary--with-link
    label: Normal (primary) link
    hidden: true
    context:
      card_title: A Normal Primary Card with Link
      theme: primary
      card_href: "JavaScript:Void(0);"
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, <a class="vf-card__link" href="JavaScript:Void(0);">consectetur</a> adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_image__alt: Image alt text
