# The title shown on the component page
title: Card
# Label shown on index pages
label: Card
status: alpha
preview: '@preview--nogrid'
collated: true
# The template used from /components/_previews
#
context:
  component-type: container
  modifier: vf-u-background-color--grey--lightest
# Per-variant options
variants:
  - name: default
    label: Default
    hidden: true
  - name: easy
    label: Easy
    hidden: false
    context: 
      card: 
        card_title: A Easy Card Title 1
        card_href: http://www.hello.com
        modifier: vf-card--easy
        card_image: ../../assets/vf-card/assets/vf-card-example.png
        card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: normal
    label: Normal
    hidden: false
    context: 
      card: 
        card_title: A Normal Card Title 1
        card_href: http://www.hello.com
        modifier: vf-card--normal
        card_image: ../../assets/vf-card/assets/vf-card-example.png
        card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: normal--primary
    label: Normal (primary)
    context: 
      card: 
        card_title: Normal Card with primary accent
        card_href: http://www.hello.com
        modifier: vf-card--normal vf-card-theme--primary
        card_image: ../../assets/vf-card/assets/vf-card-example.png
        card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: normal--secondary
    label: Normal (secondary)
    context: 
      card: 
        modifier: vf-card--normal vf-card-theme--secondary
        card_title: A Normal Card with secondary accent 
        card_image: ../../assets/vf-card/assets/vf-card-example.png
        card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: normal--tertiary
    label: Normal (tertiary)
    context: 
      card: 
        modifier: vf-card--normal vf-card-theme--tertiary
        card_title: A Normal Card with tertiary accent
        card_image: ../../assets/vf-card/assets/vf-card-example.png
        card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: normal--quaternary
    label: Normal (quaternary)
    context: 
      card: 
        modifier: vf-card--normal vf-card-theme--quaternary
        card_title: A Normal Card with quaternary accent
        card_image: ../../assets/vf-card/assets/vf-card-example.png
        card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: medium
    label: Medium
    context: 
      card: 
        card_title: A Medium Card 
        card_href: http://www.hello.com
        modifier: vf-card--medium
        card_image: ../../assets/vf-card/assets/vf-card-example.png
        card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: medium--primairy
    label: Medium (primary)
    context: 
      card: 
        card_title: A Medium Card with primairy accent
        card_href: http://www.hello.com
        modifier: vf-card--medium vf-card-theme--primary
        card_image: ../../assets/vf-card/assets/vf-card-example.png
        card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: medium--secondary
    label: Medium (secondary)
    hidden: false
    context: 
      card: 
        modifier: vf-card--medium vf-card-theme--secondary
        card_title: A Medium Card with secondary accent
        card_image: ../../assets/vf-card/assets/vf-card-example.png
        card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: medium--tertiary
    label: Medium (tertiary)
    hidden: false
    context: 
      card: 
        modifier: vf-card--medium vf-card-theme--tertiary
        card_title: A Medium Card with tertiary accent
        card_image: ../../assets/vf-card/assets/vf-card-example.png
        card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: medium--quaternary
    label: Medium (quaternary)
    hidden: false
    context: 
      card: 
        modifier: vf-card--medium vf-card-theme--quaternary
        card_title: A Medium Card with quaternary accent
        card_image: ../../assets/vf-card/assets/vf-card-example.png
        card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  # section_title: Missions
  # href: www.test. com
  # section__subheading: To promote molecular biology across Europe
  # card:
  # custom-values: passed as {{custom-values}}
  # title: Title text
  # text: String of text
  # image: ../../assets/vf-component-name/assets/vf-component-name.png
  # - note on paths: be sure to prefix with `../../`
  # - Why? https://github.com/visual-framework/vf-core/issues/364




