# The title shown on the component page
title: Card
# Label shown on index pages
label: Card
status: live
# The template used from /components/_previews

context:
  component-type: block
  # custom-values: passed as {{custom-values}}

  title: Title Block
  text: two lines of text
  image: ../../assets/vf-card/assets/vf-card-example.png

variants:
  - name: default
    hidden: true
  - name: topic-card
    context:
      title: Title Block
      text: two lines of text
      modifier: vf-card--topic
  - name: as-link
    context:
      title: Title Block
      text: two lines of text
      card_href: https://www.emmbl.de
      modifier: vf-card--topic
  - name: navigation-card
    context:
      title: Title Block
      text: two lines of text
      modifier: vf-card--navigation
