# The title shown on the component page
title: Card
# Label shown on index pages
label: Card
status: alpha
# The template used from /components/_previews
#
# Per-variant options
# variants:
  # - name: default
  #   hidden: true
context:
  component-type: block
  # custom-values: passed as {{custom-values}}

  title: Title Block
  text: two lines of text
  image: ../../assets/vf-card/assets/vf-card-example.png
