# The title shown on the component page
title: Card
# Label shown on index pages
label: Card
status: alpha
# preview: '@preview--nogrid'
collated: true
# The template used from /components/_previews
#
context:
  component-type: block
  # modifier: vf-u-background-color--grey--lightest
# Per-variant options
variants:
  - name: default
    label: Default
    hidden: true
  - name: very-easy
    label: Very Easy
    hidden: false
    context:
      card_title: A Easy Card Title 1
      variant: very-easy
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: easy
    label: Easy
    hidden: false
    context:
      card_title: A Easy Card Title 2
      variant: easy
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: easy--primary
    label: Easy (primary)
    context:
      card_title: Easy Card with primary accent
      theme: primary
      variant: easy
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: easy--secondary
    label: Easy (secondary)
    context:
      theme: secondary
      variant: easy
      card_title: A Easy Card with secondary accent
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: easy--tertiary
    label: Easy (tertiary)
    context:
      theme: tertiary
      variant: easy
      card_title: A Easy Card with tertiary accent
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: easy--quaternary
    label: Easy (quaternary)
    context:
      theme: quaternary
      variant: easy
      card_title: A Easy Card with quaternary accent
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: normal
    label: Normal
    context:
      card_title: A Normal Card
      variant: normal
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: normal--primary
    label: Normal (primary)
    context:
      card_title: A Normal Card with primary accent
      theme: primary
      variant: normal
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: normal--secondary
    label: Normal (secondary)
    hidden: false
    context:
      theme: secondary
      variant: normal
      card_title: A Normal Card with secondary accent
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: normal--tertiary
    label: Normal (tertiary)
    hidden: false
    context:
      theme: tertiary
      variant: normal
      card_title: A Normal Card with tertiary accent
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: normal--quaternary
    label: Normal (quaternary)
    hidden: false
    context:
      theme: quaternary
      variant: normal
      card_title: A Normal Card with quaternary accent
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: normal--primary--with-link
    label: Normal (primary) link
    context:
      card_title: A Normal Primary Card with Link
      theme: primary
      variant: normal
      card_href: "https://www.alwaystwisted.com"
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, <a href="#">consectetur</a> adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
