title: EMBL Content meta properties
label: EMBL Content meta properties
preview: '@preview--blocks'
status: alpha
context:
  pattern-type: block
  meta-who: all
  meta-what: services, websites
  meta-where: EMBL
  meta-active: what
  meta-utility: -8
  meta-reach: -5
  meta-maintainer: Strategy and Communications
  meta-last-review: 2019-01-20
  meta-review-cycle: 180
  meta-expiry: 2019-06-20
