title: EMBL Content meta properties
label: EMBL Content meta properties

status: alpha
context:
  component-type: embl-block
  meta_who: all
  meta_what: services, websites
  meta_where: EMBL
  meta_active: what
  meta_utility: -8
  meta_reach: -5
  meta_maintainer: Strategy and Communications
  meta_last-review: "2019-01-20"
  meta_review-cycle: 180
  meta_expiry: "2019-06-20"
