# The title shown on the component page
title: Show more
# Label shown on index pages
label: Show more
status: beta
# The template used from /components/_previews
#
# Per-variant options
variants:
  - name: default
    label: Default
    context:
      showmore_content: Something small enough to escape casual notice.
context:
  component-type: utility
