title: Tree
label: Tree
status: alpha

context:
  component-type: block
  tree_example_href: 'JavaScript:Void(0);'
variants:
  - name: default
    label: Level 1, closed
    context:
      expanded: false
      vf_tree_list:
        - title: Course Overview
          sublist: false
        - title: What is bioinformatics?
          expanded: false
          sublist:
            - title: Subitems
        - title: The role of public databases
          expanded: false
          sublist:
            - title: Subitems
        - title: What makes a good bioinformatics database?
          expanded: false
          sublist:
            - title: Subitems
        - title: Tips on managing and sharing data?
          expanded: false
          sublist:
            - title: Subitems
        - title: Where do I submit my data?
          expanded: false
          sublist:
            - title: Subitems
        - title: Using ontologies to provide controlled vocabularies
          expanded: false
          sublist:
            - title: Subitems
        - title: Summary
          expanded: false
          sublist:
            - title: Subitems
        - title: Get help and support
          expanded: false
          sublist:
            - title: Subitems
  - name: open 2
    label: Level 2
    context:
      expanded: true
      vf_tree_list:
        - title: Course Overview
        - title: What is bioinformatics?
          expanded: false
          sublist:
            - title: Subitems
        - title: The role of public databases
          expanded: false
          sublist:
            - title: Subitems
        - title: What makes a good bioinformatics database?
          expanded: true
          artiveTrail: true
          sublist:
            - title: Primary and secondary databases
            - title: Describing data consistently
            - title: Minimum information standards
            - title: Controlled vocabularies
        - title: Tips on managing and sharing data?
          expanded: false
          sublist:
            - title: Subitems
        - title: Where do I submit my data?
          expanded: false
          sublist:
            - title: Subitems
        - title: Using ontologies to provide controlled vocabularies
          expanded: false
          sublist:
            - title: Subitems
        - title: Summary
          expanded: false
          sublist:
            - title: Subitems
        - title: Get help and support
          expanded: false
          sublist:
            - title: Subitems
  - name: open 3
    label: Level 3
    context:
      expanded: true
      vf_tree_list:
        - title: Course Overview
          sublist: false
        - title: What is bioinformatics?
          expanded: false
          sublist:
            - title: Subitems
        - title: The role of public databases
          expanded: false
          sublist:
            - title: Subitems
        - title: What makes a good bioinformatics database?
          expanded: true
          artiveTrail: true
          sublist:
            - title: Primary and secondary databases
            - title: Describing data consistently
            - title: Minimum information standards
            - title: Controlled vocabularies
              expanded: true
              sublist:
                - title: Non-heirarchial list
                  artiveTrail: true
                - title: Taxonomy
                - title: Thesaurus
                - title: Gene Ontology
        - title: Tips on managing and sharing data?
          expanded: false
          sublist:
            - title: Subitems
        - title: Where do I submit my data?
          expanded: false
          sublist:
            - title: Subitems
        - title: Using ontologies to provide controlled vocabularies
          expanded: false
          sublist:
            - title: Subitems
        - title: Summary
          expanded: false
          sublist:
            - title: Subitems
        - title: Get help and support
          expanded: false
          sublist:
            - title: Subitems
