title: Button
label: Button

status: beta
context:
  component-type: element


variants:
  - name: default
    hidden: true
    context:
      text: alpha
  - name: primary
    context:
      text: a primary button
      theme: primary
  - name: secondary
    context:
      text: a secondary button
      theme: secondary
  - name: tertiary
    context:
      text: a tertiary button
      theme: tertiary
  - name: small
    context:
      text: a small button
      theme: primary
      style: ["s"]
  - name: regular
    context:
      text: a regular button
      theme: primary
      style: ["r"]
  - name: large
    context:
      text: a large button
      theme: primary
      style: ["l"]
  - name: pill
    context:
      text: a pill style
      style: ["pill"]
      theme: primary
  - name: rounded
    context:
      text: a rounded style
      style: ["rounded"]
      theme: primary
  - name: outline
    context:
      text: an outline style
      style: ["outline"]
      theme: primary
  - name: link
    context:
      text: an link variant
      href: https://example.com/
      theme: primary
