# The title shown on the component page
title: Hero
# Label shown on index pages
label: Hero
status: alpha
preview: '@preview--nogrid'
# The template used from /components/_previews
#
# Per-variant options
# variants:
  # - name: default
  #   hidden: true
context:
  component-type: container

  vf_hero_link: https://example.com/
  vf_hero_text: The Hentze group combines biochemical and systemsâ€“level approaches to investigate the connections between gene expression and cell metabolism, and their roles in human disease.
  vf_hero_link_text: Learn more.

  vf_hero_heading: About the Hentze group
