# The title shown on the component page
title: Hero
# Label shown on index pages
label: Hero
status: alpha
preview: '@preview--nogrid'
# The template used from /components/_previews
#
# Per-variant options
# variants:
  # - name: default
  #   hidden: true
context:
  component-type: container
  modifier_class: vf-hero--easy
  vf_hero_href: 'JavaScript:Void(0);'
  vf_hero_subheading: an example of some ancillary text
  vf_hero_text:
    - The Hentze group combines biochemical and systems–level approaches to investigate the connections between gene expression and cell metabolism, and their roles in human disease.
  vf_hero_link_text: Learn more.
  vf_hero_heading: About the Hentze group!
  vf_hero_image: url('https://acxngcvroo.cloudimg.io/v7/https://www.embl.org/files/wp-content/uploads/vf-hero-intense.png');
variants:
  - name: default
    hidden: true
  - name: example
    hidden: true
  - name: very easy
    context:
      modifier_class: vf-hero--very-easy
  - name: easy
    context:
      modifier_class: vf-hero--easy
  - name: normal
    context:
      modifier_class: vf-hero--normal
  - name: hard
    context:
      modifier_class: vf-hero--hard
  - name: extreme
    hidden: true
    context:
      modifier_class: vf-hero--extreme
  - name: intense
    context:
      vf_hero_summary_title: Europe wide, global impact, infinite curiosity.
      vf_hero_href: https://www.embl.de/aboutus/general_information/mission/index.html
      vf_hero_text: Learn more about EMBL’s contribution to society
      modifier_class: vf-hero--intense
  - name: primary
    context:
      modifier_class: vf-hero-theme--primary
  - name: secondary
    context:
      modifier_class: vf-hero-theme--secondary
  - name: tertiary
    context:
      modifier_class: vf-hero-theme--tertiary
