title: Box
label: Box
status: live
context:
  component-type: block
variants:
  - name: default
    hidden: true
    context:
      box:
        box_href: "JavaScript:Void(0);"
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
  - name: is a link
    context:
      box:
        box_href: "JavaScript:Void(0);"
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--is-link
  - name: easy
    hidden: true
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--easy
  - name: normal
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--normal
  - name: normal (primary)
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--normal vf-box-theme--primary
  - name: normal (secondary)
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--normal vf-box-theme--secondary
  - name: normal (tertiary)
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--normal vf-box-theme--tertiary
  - name: normal (quaternary)
    hidden: true
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--normal vf-box-theme--quaternary
  - name: normal (quinary)
    hidden: true
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--normal vf-box-theme--quinary
  - name: medium
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--medium
  - name: medium (primary)
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--medium vf-box-theme--primary
  - name: medium (secondary)
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--medium vf-box-theme--secondary
  - name: medium (tertiary)
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--medium vf-box-theme--tertiary
  - name: medium (quaternary)
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--medium vf-box-theme--quaternary
  - name: medium (quinary)
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--medium vf-box-theme--quinary
  - name: hard
    hidden: true
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--hard
  - name: extreme
    hidden: true
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--extreme
  - name: intense
    hidden: true
    context:
      box:
        box_heading: Did You Know?
        box_text: This is some more content that would be in the box.
        box_modifier: vf-box--intense
  - name: factoid
    hidden: true
    context:
      box:
        box_heading: Did You Know?
        box_text: Invasive cancer is the leading cause of death in the developed world and the second leading in the developing world.
        box_modifier: vf-box--factoid
        deprecated_text: vf-box--factoid is now deprecated, please use `vf-box--theme--primary`
  - name: inlay
    hidden: true
    context:
      box:
        box_heading: About the Häring Group
        box_text: The Sharpe group brings together an interdisciplinary team of biologists, physicists and computer scientists to build a multi-scale computer simulation of a paradigm of organogenesis – mammalian limb development.
        box_modifier: vf-box--inlay
        deprecated_text: vf-box--inlay is now deprecated, please use `vf-box--theme--quaternary`
