title: Badge
label: Badge
status: live
context:
  component-type: element
variants:
  - name: default
    hidden: true
    context:
      text: alpha

  - name: primary
    context:
      text: alpha
      theme: primary

  - name: secondary
    context:
      text: alpha
      theme: secondary

  - name: tertiary
    context:
      text: alpha
      theme: tertiary

  - name: link - primary
    context:
      badge_href: "JavaScript:Void(0);"
      theme: primary
      text: beta
