title: Badges
label: Badges
status: alpha
context:
  component-type: element
variants:
  - name: default
    context:
      text: alpha
  - name: primary
    context:
      style: ["outline" , "rounded"]
      text: alpha
      theme: primary
  - name: secondary
    context:
      text: beta
      theme: secondary
  - name: tertiary
    context:
      text: alpha
      theme: tertiary
      override_class: "your-extra-class"
      id: "your-id"
  - name: outline
    context:
      text: alpha
      style: ["outline"]
  - name: rounded
    context:
      text: alpha
      style: ["rounded"]
  - name: pill
    context:
      text: alpha
      style: ["pill"]
  - name: square
    context:
      style: ["square"]
      theme: primary
  - name: phases
    context:
      text: alpha
      theme: tertiary
  - name: link
    context:
      badge_href: http://www.metallica.com
      text: beta
